### ISSUE TITLE
Swap out all `env_value()` calls for `value()`

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape-tools#14]
`value(<field name>)` is a more robust version of `env_value(<env var name>)` that dynamically decides which version of the object field to load depending on the context and execution environment. All tools should be updated to use it instead of `env_value`.

**Comment by omidroshani** [comment]
I'm interested in collaborating on it. Could you please let me know if I can work on this issue?

**Comment by kyleroche** [comment]
Go for it. Should be a quick one. Looking forward to the PR

**Comment by vasinov** [comment]
With the latest update, tools reference props directly. This issue is no longer relevant.
